export const JOB_TYPE_LOAD_REQUEST = "JOB_TYPE_LOAD_REQUEST";
export const JOB_TYPE_LOAD_SUCCESS = "JOB_TYPE_LOAD_SUCCESS";
export const JOB_TYPE_LOAD_FAIL = "JOB_TYPE_LOAD_FAIL";
export const JOB_TYPE_LOAD_RESET = "JOB_TYPE_LOAD_RESET";

export const JOB_TYPE_UPDATE_REQUEST = "JOB_TYPE_UPDATE_REQUEST";
export const JOB_TYPE_UPDATE_SUCCESS = "JOB_TYPE_UPDATE_SUCCESS";
export const JOB_TYPE_UPDATE_FAIL = "JOB_TYPE_UPDATE_FAIL";

export const JOB_TYPE_DELETE_REQUEST = "JOB_TYPE_DELETE_REQUEST";
export const JOB_TYPE_DELETE_SUCCESS = "JOB_TYPE_DELETE_SUCCESS";
export const JOB_TYPE_DELETE_FAIL = "JOB_TYPE_DELETE_FAIL";
