export const JOB_TIME_LOAD_REQUEST = "JOB_TIME_LOAD_REQUEST";
export const JOB_TIME_LOAD_SUCCESS = "JOB_TIME_LOAD_SUCCESS";
export const JOB_TIME_LOAD_FAIL = "JOB_TIME_LOAD_FAIL";
export const JOB_TIME_LOAD_RESET = "JOB_TIME_LOAD_RESET";